image: gradle:7.3.0-jdk17-alpine

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - export DOCKER_HOST="tcp://63.250.53.90:2375"
  - export GRADLE_USER_HOME=`pwd`/.gradle

services:
  - docker:dind

stages:
  - build
  - docker-push

gradle-build-stage:
  stage: build
  script:
    - ./gradlew clean build --no-daemon
  only:
    - merge_requests

gradle-docker-push:
  stage: docker-push
  script:
    - ./gradlew dockerPush --no-daemon
  only:
    - merge_requests

#deploy-to-k8s:
#  stage: deploy
#  image: bitnami/kubectl
#  script:
#    - kubectl apply -f k8s/ms5-demo/ -n ms5-demo-dev
#  only:
#    - merge_requests

