image: gradle:6.9.1-jdk17

variables:
  DOCKER_DRIVER: overlay2
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  
before_script:
  # - export DOCKER_HOST="tcp://localhost:2375"
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export DOCKER_HOST="tcp://docker:2376"
  - export DOCKER_TLS_CERTDIR="/certs"

stages:
  - build
  - docker-push

gradle-build-stage:
  stage: build
  script:
    - ./gradlew clean build --no-daemon
  only:
    - merge_requests

gradle-docker-push:
  stage: docker-push
  script:
    - ./gradlew dockerPush --no-daemon
  only:
    - merge_requests
#deploy-to-k8s:
#  stage: deploy
#  image: bitnami/kubectl
#  script:
#    - kubectl apply -f k8s/ms5-demo/ -n ms5-demo-dev
#  only:
#    - merge_requests

