services:

  db:
    hostname: postgres
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot_db
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  adminer:
    hostname: postgres
    image: adminer
    restart: always
    ports:
      - 9090:8080

volumes:
  pg-data: